baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Test Hugo Site'
theme = 'ananke'

[[deployment.targets]]
 URL = "s3://test?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"